/* File automatically generated by the macro OPENCOG_ADD_ATOM_TYPES. Do not edit */
#include <opencog/atomspace/types.h>
namespace opencog
{
extern opencog::Type FOO_NODE;
extern opencog::Type BAR_NODE;
extern opencog::Type FOOBAR_LINK;
} // namespace opencog
