
; DO NOT EDIT THIS FILE! This file was automatically
; generated from atom definitions in types.script by the macro OPENCOG_ADD_ATOM_TYPES
;
; This file contains basic scheme wrappers for atom creation.
;
(define-module (opencog))
(define-public FooNodeType (cog-type->int 'FooNode))
(define-public (FooNode . x)
	(apply cog-new-node (append (list FooNodeType) x)))
(define-public BarNodeType (cog-type->int 'BarNode))
(define-public (BarNode . x)
	(apply cog-new-node (append (list BarNodeType) x)))
(define-public FoooooobarLinkType (cog-type->int 'FoooooobarLink))
(define-public (FoooooobarLink . x)
	(apply cog-new-link (append (list FoooooobarLinkType) x)))
