/* File automatically generated by the macro OPENCOG_ADD_ATOM_TYPES. Do not edit */
#include <opencog/atomspace/types.h>
namespace opencog
{
extern opencog::Type SPACE_MAP_NODE;
extern opencog::Type OBJECT_NODE;
extern opencog::Type BLOCK_ENTITY_NODE;
extern opencog::Type STRUCTURE_NODE;
extern opencog::Type IMAGINARY_STRUCTURE_NODE;
extern opencog::Type TIME_NODE;
extern opencog::Type AT_TIME_LINK;
extern opencog::Type LATEST_LINK;
extern opencog::Type BEFORE_LINK;
extern opencog::Type OVERLAPS_LINK;
extern opencog::Type DURING_LINK;
extern opencog::Type MEETS_LINK;
extern opencog::Type STARTS_LINK;
extern opencog::Type FINISHES_LINK;
extern opencog::Type EQUALS_LINK;
extern opencog::Type AFTER_LINK;
extern opencog::Type OVERLAPPED_BY_LINK;
extern opencog::Type CONTAINS_LINK;
extern opencog::Type MET_BY_LINK;
extern opencog::Type STARTED_BY_LINK;
extern opencog::Type FINISHED_BY_LINK;
} // namespace opencog
