/* File automatically generated by the macro OPENCOG_ADD_ATOM_TYPES. Do not edit */
#include <opencog/atomspace/types.h>
namespace opencog
{
extern opencog::Type PREDICTIVE_IMPLICATION_LINK;
extern opencog::Type TAIL_PREDICTIVE_IMPLICATION_LINK;
extern opencog::Type PREDICTIVE_ATTRACTION_LINK;
extern opencog::Type SIMULTANEOUS_AND_LINK;
extern opencog::Type EVENTUAL_SEQUENTIAL_AND_LINK;
extern opencog::Type EVENTUAL_PREDICTIVE_IMPLICATION_LINK;
extern opencog::Type EXTENSIONAL_SIMILARITY_LINK;
extern opencog::Type INTENSIONAL_SIMILARITY_LINK;
extern opencog::Type INTENSIONAL_INHERITANCE_LINK;
extern opencog::Type AT_TIME_LINK;
extern opencog::Type ONTOLOGICAL_INHERITANCE_LINK;
} // namespace opencog
