/* File automatically generated by the macro OPENCOG_ADD_ATOM_TYPES. Do not edit */
#include <opencog/atomspace/types.h>
namespace opencog
{
extern opencog::Type PET_NODE;
extern opencog::Type AVATAR_NODE;
extern opencog::Type ACCESSORY_NODE;
extern opencog::Type HUMANOID_NODE;
extern opencog::Type UNKNOWN_OBJECT_NODE;
extern opencog::Type IS_ACCEPTABLE_SECOND_ARG_LINK;
extern opencog::Type ONTOLOGICAL_INHERITANCE_LINK;
extern opencog::Type WR_LINK;
extern opencog::Type FREQUENCY_LINK;
extern opencog::Type FEELING_NODE;
extern opencog::Type PHRASE_NODE;
extern opencog::Type SPEECH_ACT_TRIGGER_NODE;
extern opencog::Type SPEECH_ACT_SCHEMA_NODE;
extern opencog::Type DIALOG_NODE;
extern opencog::Type UTTERANCE_NODE;
extern opencog::Type DEFINED_FRAME_NODE;
extern opencog::Type DEFINED_FRAME_ELEMENT_NODE;
extern opencog::Type FRAME_ELEMENT_LINK;
extern opencog::Type SIMULTANEOUS_EQUIVALENCE_LINK;
} // namespace opencog
