/* File automatically generated by the macro OPENCOG_ADD_ATOM_TYPES. Do not edit */
#include <opencog/atomspace/types.h>
namespace opencog
{
#ifndef _OPENCOG_NOTYPE_
#define _OPENCOG_NOTYPE_
// Set notype's code with the last possible Type code
static const opencog::Type NOTYPE=((Type) -1);
#endif // _OPENCOG_NOTYPE_
extern opencog::Type ATOM;
extern opencog::Type NODE;
extern opencog::Type LINK;
extern opencog::Type CONCEPT_NODE;
extern opencog::Type NUMBER_NODE;
extern opencog::Type ORDERED_LINK;
extern opencog::Type UNORDERED_LINK;
extern opencog::Type SET_LINK;
extern opencog::Type LIST_LINK;
extern opencog::Type MEMBER_LINK;
extern opencog::Type SUBSET_LINK;
extern opencog::Type AND_LINK;
extern opencog::Type OR_LINK;
extern opencog::Type NOT_LINK;
extern opencog::Type SEQUENTIAL_AND_LINK;
extern opencog::Type ABSENT_LINK;
extern opencog::Type CONTEXT_LINK;
extern opencog::Type TYPE_NODE;
extern opencog::Type TYPE_CHOICE;
extern opencog::Type VARIABLE_NODE;
extern opencog::Type TYPED_VARIABLE_LINK;
extern opencog::Type VARIABLE_LIST;
extern opencog::Type QUOTE_LINK;
extern opencog::Type LAMBDA_LINK;
extern opencog::Type DEFINE_LINK;
extern opencog::Type COMPOSE_LINK;
extern opencog::Type SATISFACTION_LINK;
extern opencog::Type BIND_LINK;
extern opencog::Type FORALL_LINK;
extern opencog::Type EXISTS_LINK;
extern opencog::Type AVERAGE_LINK;
extern opencog::Type SATISFYING_SET_LINK;
extern opencog::Type SCHOLEM_LINK;
extern opencog::Type IMPLICATION_LINK;
extern opencog::Type EQUIVALENCE_LINK;
extern opencog::Type EVALUATION_LINK;
extern opencog::Type ASSOCIATIVE_LINK;
extern opencog::Type INHERITANCE_LINK;
extern opencog::Type SIMILARITY_LINK;
extern opencog::Type ATTRACTION_LINK;
extern opencog::Type PROCEDURE_NODE;
extern opencog::Type GROUNDED_PROCEDURE_NODE;
extern opencog::Type SCHEMA_NODE;
extern opencog::Type GROUNDED_SCHEMA_NODE;
extern opencog::Type PREDICATE_NODE;
extern opencog::Type GROUNDED_PREDICATE_NODE;
extern opencog::Type DEFINED_RELATIONSHIP_NODE;
extern opencog::Type SCHEMA_EXECUTION_LINK;
extern opencog::Type SCHEMA_EVALUATION_LINK;
extern opencog::Type EXECUTION_LINK;
extern opencog::Type EXECUTION_OUTPUT_LINK;
extern opencog::Type ANCHOR_NODE;
extern opencog::Type QUANTITY_LINK;
extern opencog::Type PLUS_LINK;
extern opencog::Type TIMES_LINK;
extern opencog::Type GREATER_THAN_LINK;
} // namespace opencog
